-- Rollback initial schema

DROP TABLE IF EXISTS mod CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS post_votes CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS subnoddits CASCADE;
DROP TABLE IF EXISTS users CASCADE;
